### ISSUE TITLE
Issues when multiple remotes exist

### ISSUE THREAD

**Issue by jmklonowski** [Ricky54326/Github-Auto-Issue-Creator#228]
Some remotes are added to the .git/config file in the following format:

[remote "username"]
	url = git@github.com:username/Project-name.git
	fetch = +refs/heads/*:refs/remotes/username/*

Which breaks the getRepo and getOwner methods since they require the format to be: 

[remote "username"]
	url = https://github.com/username/Project-name.git
	fetch = +refs/heads/*:refs/remotes/username/*

Also, since it loops through, it will always use the last remote which may or may not be the origin

**Comment by Ricky54326** [comment]
Good now that I merged your PR?

**Comment by jmklonowski** [comment]
Yes, closing issue.
